### ISSUE TITLE
Update to work with Inky 1.3.3

### ISSUE THREAD

**Issue by alexanderlamb** [zurb/inky-cli#1]
I'll happily submit a pull request to expand inky-cli to work with inky 1.3.3 if needed

**Comment by gakimball** [comment]
Go for it!

**Comment by gakimball** [comment]
I think allowing for the latest 1.x version is fine. I don't anticipate Inky's API changing unless there's a 2.0 version. **Edit:** which is to say, we shouldn't have to bump the dependency here for 1.4, 1.5, etc.

**Comment by Hatlen** [comment]
+1

**Comment by Hatlen** [comment]
This worked for me https://github.com/zurb/inky-cli/pull/2.
Didn't notice anything breaking, but I haven't done any thorough testing.
It would be very good to update the inky version and get support for e.g. wrapper tags and other stuff

**Comment by gakimball** [comment]
Merged #2, thanks @Hatlen! Released inky-cli 1.0.1.
